[logger]
level = "ERROR"

[client]
showErrorDetails = false

[server]
enableStaticServing = true
enableCORS = false

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[deprecation]
showPyplotGlobalUse = false 